server:
  port: 8081
  config: default

spring:
  profiles:
    # 激活的文件，会覆盖本文件的值
    # 激活的文件，spring.profiles.active 无效
    # 激活的文件，spring.profiles.include 会覆盖本文件的值
    # 包含的文件，spring.profiles.active 有效，继续递归则参考以上三点
    # 包含的文件，spring.profiles.include 有效
    active: dev
  datasource:
      druid:
        sso:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/sso?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: www.kfyty.com
          initial-size: 5
          min-idle: 5
          max-active: 100
          keep-alive: true
          min-evictable-idle-time-millis: 28740000
          max-evictable-idle-time-millis: 28800000
        test:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: www.kfyty.com
          initial-size: 5
          min-idle: 5
          max-active: 100
          keep-alive: true
          min-evictable-idle-time-millis: 28740000
          max-evictable-idle-time-millis: 28800000

mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    map-underscore-to-camel-case: true

logging:
  level:
    com.kfyty.mybatis.auto.mapper: debug
    com.kfyty.mybatis.auto.mapper.handle: info
    com.kfyty.dynamic.mapper.sso: debug
    com.kfyty.dynamic.mapper.test: debug
