spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: www.kfyty.com
    timeout: 3000
    lettuce:
      pool:
        min-idle: 2
        max-idle: 3
        max-active: 8
        max-wait: 3000ms
        time-between-eviction-runs: 5000ms

logging:
  level:
    com.kfyty.mybatis.auto.mapper: debug
    com.kfyty.mybatis.auto.mapper.handle: info
